export const quizQuestions = [
  {
    id: 1,
    category: "Consumo Diário",
    emoji: "📊",
    difficulty: "Fácil",
    question: "Quanto açúcar um brasileiro consome em média por dia?",
    options: [
      { id: "a", text: "25 gramas (5 colheres de chá)" },
      { id: "b", text: "50 gramas (10 colheres de chá)" },
      { id: "c", text: "80 gramas (16 colheres de chá)" },
      { id: "d", text: "10 gramas (2 colheres de chá)" },
    ],
    correct: "c",
    explanation:
      "O brasileiro consome em média 80g de açúcar por dia! Isso é mais do que o dobro da recomendação da OMS, que é de até 50g. Nossa saúde pede socorro! 😱",
  },
  {
    id: 2,
    category: "Doenças",
    emoji: "🦷",
    difficulty: "Fácil",
    question: "Qual doença nos dentes é causada pelo consumo excessivo de açúcar?",
    options: [
      { id: "a", text: "Gengivite" },
      { id: "b", text: "Cárie dentária" },
      { id: "c", text: "Tártaro" },
      { id: "d", text: "Halitose" },
    ],
    correct: "b",
    explanation:
      "A cárie dentária é causada por bactérias que se alimentam do açúcar que comemos e produzem ácidos que destroem o esmalte dos dentes. Por isso é tão importante escovar os dentes depois de comer doces! 🦷",
  },
  {
    id: 3,
    category: "Tipos de Açúcar",
    emoji: "🍯",
    difficulty: "Médio",
    question: "Qual destes NÃO é um tipo de açúcar?",
    options: [
      { id: "a", text: "Frutose (açúcar das frutas)" },
      { id: "b", text: "Lactose (açúcar do leite)" },
      { id: "c", text: "Proteína (dos músculos)" },
      { id: "d", text: "Glicose (açúcar do sangue)" },
    ],
    correct: "c",
    explanation:
      "A proteína não é um açúcar! Os açúcares (carboidratos) incluem frutose (frutas), lactose (leite), glicose (sangue), sacarose (açúcar de mesa). Proteínas são nutrientes completamente diferentes, usados para construir músculos! 💪",
  },
  {
    id: 4,
    category: "Alimentos",
    emoji: "🥤",
    difficulty: "Fácil",
    question: "Quantos gramas de açúcar tem aproximadamente uma lata de refrigerante (350ml)?",
    options: [
      { id: "a", text: "5 gramas" },
      { id: "b", text: "15 gramas" },
      { id: "c", text: "38 gramas" },
      { id: "d", text: "60 gramas" },
    ],
    correct: "c",
    explanation:
      "Uma lata de refrigerante tem cerca de 38 gramas de açúcar – quase 8 colheres de chá em um único copo! Impressionante, né? Isso já passa de 75% da sua cota diária recomendada! 🥤",
  },
  {
    id: 5,
    category: "Saúde",
    emoji: "⚡",
    difficulty: "Médio",
    question: "O que acontece com o nosso corpo quando comemos muito açúcar de uma vez?",
    options: [
      { id: "a", text: "Ficamos mais fortes e inteligentes" },
      { id: "b", text: "Temos um pico de energia seguido de cansaço e irritação" },
      { id: "c", text: "Dormimos melhor à noite" },
      { id: "d", text: "Nossos músculos crescem mais rápido" },
    ],
    correct: "b",
    explanation:
      "Quando comemos muito açúcar, o sangue fica cheio de glicose rapidamente (pico glicêmico), o pâncreas libera muita insulina, e depois vem uma queda brusca – causando cansaço, irritação e mais fome. É a famosa 'ressaca do açúcar'! ⚡",
  },
  {
    id: 6,
    category: "Mitos e Verdades",
    emoji: "🔍",
    difficulty: "Difícil",
    question: "MITO ou VERDADE: O açúcar mascavo é muito mais saudável que o açúcar branco e pode ser consumido à vontade?",
    options: [
      { id: "a", text: "Verdade – açúcar mascavo é completamente saudável" },
      { id: "b", text: "Mito – ambos têm quantidades similares de calorias e devem ser consumidos com moderação" },
      { id: "c", text: "Verdade – açúcar mascavo não causa diabetes" },
      { id: "d", text: "Mito – o açúcar branco é mais saudável" },
    ],
    correct: "b",
    explanation:
      "MITO! O açúcar mascavo tem alguns minerais a mais, mas a diferença nutricional é mínima. Ambos têm cerca de 4 calorias por grama e elevam o açúcar no sangue de forma similar. A moderação é sempre necessária! 🤔",
  },
  {
    id: 7,
    category: "Diabetes",
    emoji: "💉",
    difficulty: "Médio",
    question: "O consumo excessivo de açúcar pode causar qual doença crônica?",
    options: [
      { id: "a", text: "Gripe" },
      { id: "b", text: "Pneumonia" },
      { id: "c", text: "Diabetes tipo 2" },
      { id: "d", text: "Conjuntivite" },
    ],
    correct: "c",
    explanation:
      "O excesso de açúcar pode levar ao diabetes tipo 2, onde o corpo não consegue mais controlar o açúcar no sangue direito. É uma doença séria e cada vez mais comum em jovens no Brasil. Prevenir é o melhor remédio! 💉",
  },
  {
    id: 8,
    category: "Alimentos",
    emoji: "🍫",
    difficulty: "Médio",
    question: "Qual alimento tem mais açúcar escondido (oculto)?",
    options: [
      { id: "a", text: "Alface" },
      { id: "b", text: "Ketchup" },
      { id: "c", text: "Ovo cozido" },
      { id: "d", text: "Queijo puro" },
    ],
    correct: "b",
    explanation:
      "O ketchup tem muito açúcar escondido! Uma colher de sopa tem cerca de 4g de açúcar. Esse é o chamado 'açúcar oculto' – presente em molhos, temperos e alimentos que não parecem doces. Sempre leia os rótulos! 🍅",
  },
  {
    id: 9,
    category: "Cérebro",
    emoji: "🧠",
    difficulty: "Difícil",
    question: "Como o açúcar afeta o nosso cérebro?",
    options: [
      { id: "a", text: "Não tem nenhum efeito no cérebro" },
      { id: "b", text: "Libera dopamina, criando sensação de prazer e podendo causar dependência" },
      { id: "c", text: "Apenas ajuda na concentração" },
      { id: "d", text: "Fortalece a memória permanentemente" },
    ],
    correct: "b",
    explanation:
      "O açúcar ativa o sistema de recompensa do cérebro, liberando dopamina – o mesmo mecanismo de algumas substâncias viciantes! Por isso é tão difícil parar de comer doces. O cérebro literalmente pede mais! 🧠",
  },
  {
    id: 10,
    category: "Alternativas Saudáveis",
    emoji: "🍎",
    difficulty: "Fácil",
    question: "Qual a melhor alternativa para substituir o açúcar nos sucos?",
    options: [
      { id: "a", text: "Adoçante artificial em grande quantidade" },
      { id: "b", text: "Mel em excesso" },
      { id: "c", text: "Frutas naturais e água" },
      { id: "d", text: "Mais açúcar mascavo" },
    ],
    correct: "c",
    explanation:
      "Frutas naturais têm açúcares naturais (frutose) acompanhados de fibras, vitaminas e minerais, que ajudam o corpo a processar melhor o açúcar. Sucos naturais sem adição de açúcar ou água saborizada com frutas são ótimas escolhas! 🍎",
  },
  {
    id: 11,
    category: "OMS",
    emoji: "🌍",
    difficulty: "Médio",
    question: "Segundo a OMS (Organização Mundial da Saúde), qual é o limite IDEAL de açúcar por dia para uma pessoa?",
    options: [
      { id: "a", text: "100 gramas (20 colheres de chá)" },
      { id: "b", text: "75 gramas (15 colheres de chá)" },
      { id: "c", text: "50 gramas (10 colheres de chá) no máximo" },
      { id: "d", text: "25 gramas (5 colheres de chá) idealmente" },
    ],
    correct: "d",
    explanation:
      "A OMS recomenda no máximo 50g/dia, mas o ideal é 25g ou menos (apenas 5 colheres de chá). Isso ajuda a prevenir obesidade, diabetes, cáries e doenças cardíacas. Lembre: brasileiros consomem 80g/dia em média! 🌍",
  },
  {
    id: 12,
    category: "Rotulagem",
    emoji: "📋",
    difficulty: "Difícil",
    question: "No rótulo dos alimentos, como o açúcar pode aparecer escondido?",
    options: [
      { id: "a", text: "Apenas como 'açúcar'" },
      { id: "b", text: "Como xarope de milho, dextrose, maltose, sacarose ou frutose" },
      { id: "c", text: "Nunca aparece escondido nos rótulos" },
      { id: "d", text: "Apenas como glucose" },
    ],
    correct: "b",
    explanation:
      "O açúcar se esconde em muitos nomes difíceis no rótulo: xarope de milho de alta frutose, dextrose, maltose, sacarose, frutose, maltodextrina, e muitos outros! Por isso ler rótulos é uma super habilidade que todos devem ter! 📋",
  },
  {
    id: 13,
    category: "Corpo e Saúde",
    emoji: "💊",
    difficulty: "Médio",
    question: "Além da diabetes e cárie, o açúcar em excesso também pode causar:",
    options: [
      { id: "a", text: "Olhos melhores e cabelos mais fortes" },
      { id: "b", text: "Obesidade, inflamações, acne e problemas cardíacos" },
      { id: "c", text: "Crescimento mais rápido" },
      { id: "d", text: "Mais disposição e energia permanente" },
    ],
    correct: "b",
    explanation:
      "O excesso de açúcar causa uma série de problemas: obesidade (as calorias extras viram gordura), inflamações no corpo, acne (estimula produção de sebo), pressão alta e doenças cardíacas. Um verdadeiro vilão disfarçado! 💪",
  },
  {
    id: 14,
    category: "Mitos e Verdades",
    emoji: "🧪",
    difficulty: "Difícil",
    question: "MITO ou VERDADE: Frutas são proibidas em dietas com pouco açúcar porque têm muito açúcar?",
    options: [
      { id: "a", text: "Verdade – frutas têm muito açúcar e devem ser evitadas" },
      { id: "b", text: "Mito – frutas têm açúcar natural com fibras que controlam a absorção" },
      { id: "c", text: "Verdade – só frutas azedas são permitidas" },
      { id: "d", text: "Mito – frutas não têm açúcar algum" },
    ],
    correct: "b",
    explanation:
      "MITO! Frutas têm frutose (açúcar natural), mas também têm fibras, vitaminas e antioxidantes. As fibras controlam a velocidade de absorção do açúcar, evitando picos. São muito diferentes dos açúcares adicionados! Coma frutas! 🍓",
  },
  {
    id: 15,
    category: "Alimentação Saudável",
    emoji: "🌟",
    difficulty: "Médio",
    question: "Qual é a melhor estratégia para reduzir o açúcar na alimentação gradualmente?",
    options: [
      { id: "a", text: "Cortar tudo de uma vez e nunca mais comer doce" },
      { id: "b", text: "Substituir aos poucos: água no lugar de suco, fruta no lugar de biscoito" },
      { id: "c", text: "Comer só durante o café da manhã" },
      { id: "d", text: "Usar adoçante artificial em tudo" },
    ],
    correct: "b",
    explanation:
      "A melhor estratégia é a substituição gradual! Trocar refrigerante por água com limão, biscoito por castanhas, sobremesa por fruta. Mudanças pequenas e consistentes são mais duradouras. Você consegue fazer isso! 🌟",
  },
];

export const sugarFoods = [
  {
    name: "Refrigerante",
    emoji: "🥤",
    amount: "350ml",
    sugar: 38,
    teaspoons: 7.6,
    color: "from-red-400 to-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-300",
    level: "Altíssimo",
    levelColor: "bg-red-500",
  },
  {
    name: "Achocolatado",
    emoji: "🍫",
    amount: "200ml",
    sugar: 28,
    teaspoons: 5.6,
    color: "from-amber-600 to-amber-800",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-300",
    level: "Alto",
    levelColor: "bg-amber-500",
  },
  {
    name: "Biscoito Recheado",
    emoji: "🍪",
    amount: "2 unidades",
    sugar: 20,
    teaspoons: 4,
    color: "from-yellow-400 to-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-300",
    level: "Alto",
    levelColor: "bg-orange-500",
  },
  {
    name: "Iogurte com Fruta",
    emoji: "🥛",
    amount: "170g",
    sugar: 14,
    teaspoons: 2.8,
    color: "from-pink-400 to-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-300",
    level: "Médio",
    levelColor: "bg-yellow-500",
  },
  {
    name: "Suco de Caixinha",
    emoji: "🧃",
    amount: "200ml",
    sugar: 26,
    teaspoons: 5.2,
    color: "from-orange-400 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-300",
    level: "Alto",
    levelColor: "bg-orange-500",
  },
  {
    name: "Brigadeiro",
    emoji: "🍬",
    amount: "1 unidade",
    sugar: 15,
    teaspoons: 3,
    color: "from-amber-700 to-amber-900",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-400",
    level: "Médio",
    levelColor: "bg-yellow-500",
  },
  {
    name: "Barra de Cereal",
    emoji: "🌾",
    amount: "1 unidade",
    sugar: 11,
    teaspoons: 2.2,
    color: "from-lime-500 to-green-600",
    bgColor: "bg-lime-50",
    borderColor: "border-lime-300",
    level: "Médio",
    levelColor: "bg-yellow-400",
  },
  {
    name: "Maçã",
    emoji: "🍎",
    amount: "1 média",
    sugar: 19,
    teaspoons: 3.8,
    color: "from-green-400 to-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-300",
    level: "Natural",
    levelColor: "bg-green-500",
  },
];

export const sugarTypes = [
  {
    name: "Sacarose",
    nickname: "Açúcar de Mesa",
    emoji: "🧂",
    description: "É o açúcar branco que usamos no dia a dia. Vem da cana-de-açúcar ou beterraba. É formado por glicose + frutose.",
    found: "Bolos, biscoitos, refrigerantes",
    color: "bg-white border-gray-300",
    textColor: "text-gray-700",
  },
  {
    name: "Frutose",
    nickname: "Açúcar das Frutas",
    emoji: "🍓",
    description: "Açúcar natural encontrado nas frutas. Quando nas frutas, vem acompanhado de fibras que controlam a absorção.",
    found: "Frutas, mel, xarope de milho",
    color: "bg-orange-50 border-orange-300",
    textColor: "text-orange-700",
  },
  {
    name: "Glicose",
    nickname: "Açúcar do Sangue",
    emoji: "🩸",
    description: "Principal fonte de energia das células. Nosso cérebro depende dela para funcionar. O problema é o excesso.",
    found: "Pão, macarrão, arroz, mel",
    color: "bg-red-50 border-red-300",
    textColor: "text-red-700",
  },
  {
    name: "Lactose",
    nickname: "Açúcar do Leite",
    emoji: "🥛",
    description: "Açúcar natural do leite e derivados. Algumas pessoas têm intolerância e não conseguem digeri-lo direito.",
    found: "Leite, iogurte, queijo",
    color: "bg-blue-50 border-blue-300",
    textColor: "text-blue-700",
  },
  {
    name: "Maltose",
    nickname: "Açúcar do Malte",
    emoji: "🌾",
    description: "Formado por duas moléculas de glicose. Presente em alimentos fermentados e frequentemente usado em produtos industrializados.",
    found: "Cerveja, pão, cereais maltados",
    color: "bg-yellow-50 border-yellow-300",
    textColor: "text-yellow-700",
  },
  {
    name: "Xarope de Milho",
    nickname: "O Açúcar Oculto",
    emoji: "🌽",
    description: "Usado pela indústria alimentícia por ser barato. Tem alta concentração de frutose e é um dos mais prejudiciais à saúde.",
    found: "Refrigerantes, biscoitos, molhos",
    color: "bg-amber-50 border-amber-400",
    textColor: "text-amber-700",
  },
];

export const myths = [
  {
    myth: "Açúcar mascavo é completamente saudável",
    truth: "Falso! O açúcar mascavo tem poucos minerais a mais, mas tem praticamente as mesmas calorias que o branco e eleva o açúcar no sangue de forma similar. Moderação sempre!",
    verdict: "MITO",
    emoji: "🟤",
  },
  {
    myth: "Frutas são proibidas em dietas por causa do açúcar",
    truth: "Falso! Frutas têm açúcar natural com fibras, vitaminas e minerais. As fibras retardam a absorção do açúcar, tornando as frutas muito diferentes dos açúcares adicionados.",
    verdict: "MITO",
    emoji: "🍎",
  },
  {
    myth: "Refrigerante diet/zero não faz mal nenhum",
    truth: "Parcialmente falso! Eles não têm açúcar, mas os adoçantes artificiais podem afetar o microbioma intestinal e manter o vício pelo sabor doce. Água sempre é melhor!",
    verdict: "MITO PARCIAL",
    emoji: "🥤",
  },
  {
    myth: "Mel é muito mais saudável que o açúcar refinado",
    truth: "Parcialmente verdadeiro! O mel tem antioxidantes e propriedades antibacterianas, mas ainda é açúcar. Tem praticamente as mesmas calorias e também deve ser consumido com moderação.",
    verdict: "MITO PARCIAL",
    emoji: "🍯",
  },
  {
    myth: "Crianças precisam de muito açúcar para ter energia",
    truth: "Falso! Crianças precisam de energia, mas ela pode vir de carboidratos complexos (arroz, feijão, batata) que liberam energia gradualmente. O excesso de açúcar causa hiperatividade seguida de queda de energia.",
    verdict: "MITO",
    emoji: "👧",
  },
  {
    myth: "O açúcar causa diabetes diretamente",
    truth: "Parcialmente verdadeiro! O açúcar em excesso leva à obesidade, que é um fator de risco para diabetes tipo 2. Mas a diabetes envolve múltiplos fatores, incluindo genética e sedentarismo.",
    verdict: "MITO PARCIAL",
    emoji: "💉",
  },
];

export const healthyTips = [
  {
    tip: "Troque refrigerante por água com fatias de limão ou laranja",
    emoji: "💧",
    category: "Bebidas",
  },
  {
    tip: "Prefira frutas frescas ao invés de sucos de caixinha",
    emoji: "🍓",
    category: "Lanches",
  },
  {
    tip: "Leia os rótulos: procure o total de açúcar antes de comprar",
    emoji: "📋",
    category: "Compras",
  },
  {
    tip: "Substitua biscoitos recheados por castanhas ou amendoim",
    emoji: "🥜",
    category: "Lanches",
  },
  {
    tip: "Use canela ou baunilha para adoçar sem usar açúcar",
    emoji: "🌿",
    category: "Culinária",
  },
  {
    tip: "Prefira chocolate 70%+ cacau ao chocolate ao leite",
    emoji: "🍫",
    category: "Doces",
  },
  {
    tip: "Coma devagar: o cérebro demora 20 min para registrar saciedade",
    emoji: "🧠",
    category: "Hábitos",
  },
  {
    tip: "Durma bem: pouco sono aumenta o desejo por açúcar",
    emoji: "😴",
    category: "Estilo de Vida",
  },
];
